global using Carter;
global using Marten;
global using Mapster;
global using MediatR;
global using Bogus;
global using FluentValidation;
global using BuildingBlocks.CQRS;
global using BuildingBlocks.Behaviours;
global using BuildingBlocks.Exceptions.Handler;
